// Mock data for testing frontend features without database
export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    image: "/diverse-user-avatars.png",
    role: "admin" as const,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    image: "/female-user-avatar.png",
    role: "developer" as const,
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    image: "/male-user-avatar.png",
    role: "developer" as const,
  },
  {
    id: "4",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    image: "/user-avatar-woman.png",
    role: "developer" as const,
  },
]

export const mockProjects = [
  {
    id: "1",
    name: "E-commerce Platform",
    description: "Building a modern e-commerce platform with React and Node.js",
    ownerId: "1",
    owner: mockUsers[0],
    members: [
      { userId: "1", user: mockUsers[0] },
      { userId: "2", user: mockUsers[1] },
      { userId: "3", user: mockUsers[2] },
    ],
    tasks: [
      {
        id: "1",
        title: "Setup Authentication System",
        description: "Implement JWT-based authentication with login and registration",
        status: "done" as const,
        priority: "high" as const,
        labels: ["backend", "security"],
        projectId: "1",
        assigneeId: "2",
        assignee: mockUsers[1],
        project: { id: "1", name: "E-commerce Platform" },
        timelineStart: new Date("2024-01-15"),
        timelineEnd: new Date("2024-01-20"),
        estimatedHours: 16,
        loggedHours: 18,
        storyPoints: 8,
        issueType: "story" as const,
        sprintId: "1",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-20"),
        comments: [],
        logs: [],
      },
      {
        id: "2",
        title: "Design Product Catalog UI",
        description: "Create responsive product catalog with filtering and search",
        status: "in-progress" as const,
        priority: "medium" as const,
        labels: ["frontend", "ui"],
        projectId: "1",
        assigneeId: "3",
        assignee: mockUsers[2],
        project: { id: "1", name: "E-commerce Platform" },
        timelineStart: new Date("2024-01-18"),
        timelineEnd: new Date("2024-01-25"),
        estimatedHours: 24,
        loggedHours: 12,
        storyPoints: 13,
        issueType: "story" as const,
        sprintId: "1",
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-22"),
        comments: [],
        logs: [],
      },
      {
        id: "3",
        title: "Implement Payment Gateway",
        description: "Integrate Stripe payment processing for checkout flow",
        status: "todo" as const,
        priority: "critical" as const,
        labels: ["backend", "payments"],
        projectId: "1",
        assigneeId: "2",
        assignee: mockUsers[1],
        project: { id: "1", name: "E-commerce Platform" },
        timelineStart: new Date("2024-01-25"),
        timelineEnd: new Date("2024-02-01"),
        estimatedHours: 20,
        loggedHours: 0,
        storyPoints: 13,
        issueType: "story" as const,
        sprintId: "2",
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-20"),
        comments: [],
        logs: [],
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    _count: { tasks: 3 },
  },
  {
    id: "2",
    name: "Mobile App Redesign",
    description: "Redesigning the mobile app with improved UX and performance",
    ownerId: "1",
    owner: mockUsers[0],
    members: [
      { userId: "1", user: mockUsers[0] },
      { userId: "4", user: mockUsers[3] },
    ],
    tasks: [
      {
        id: "4",
        title: "User Profile Screen",
        description: "Design and implement user profile management screen",
        status: "in-progress" as const,
        priority: "medium" as const,
        labels: ["mobile", "ui"],
        projectId: "2",
        assigneeId: "4",
        assignee: mockUsers[3],
        project: { id: "2", name: "Mobile App Redesign" },
        timelineStart: new Date("2024-01-12"),
        timelineEnd: new Date("2024-01-19"),
        estimatedHours: 12,
        loggedHours: 8,
        createdAt: new Date("2024-01-12"),
        updatedAt: new Date("2024-01-18"),
        comments: [],
        logs: [],
      },
    ],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
    _count: { tasks: 1 },
  },
  {
    id: "3",
    name: "API Documentation",
    description: "Creating comprehensive API documentation for developers",
    ownerId: "2",
    owner: mockUsers[1],
    members: [
      { userId: "2", user: mockUsers[1] },
      { userId: "3", user: mockUsers[2] },
    ],
    tasks: [
      {
        id: "5",
        title: "API Endpoint Documentation",
        description: "Document all REST API endpoints with examples",
        status: "done" as const,
        priority: "low" as const,
        labels: ["documentation"],
        projectId: "3",
        assigneeId: "3",
        assignee: mockUsers[2],
        project: { id: "3", name: "API Documentation" },
        timelineStart: new Date("2024-01-05"),
        timelineEnd: new Date("2024-01-12"),
        estimatedHours: 8,
        loggedHours: 10,
        storyPoints: 5,
        issueType: "task" as const,
        sprintId: "3",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-12"),
        comments: [],
        logs: [],
      },
    ],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-15"),
    _count: { tasks: 1 },
  },
]

export const mockStatuses: TaskStatus[] = [
  {
    id: "status-todo",
    name: "To Do",
    color: "#FF6B6B",
    category: "not-started",
    order: 1
  },
  {
    id: "status-in-progress",
    name: "In Progress",
    color: "#4ECDC4",
    category: "in-progress",
    order: 2
  },
  {
    id: "status-done",
    name: "Done",
    color: "#45B7D1",
    category: "completed",
    order: 3
  },
  // Custom statuses
  {
    id: "status-review",
    name: "In Review",
    color: "#FFA07A",
    category: "in-progress",
    order: 4
  },
  {
    id: "status-blocked",
    name: "Blocked",
    color: "#FF4500",
    category: "not-started",
    order: 5
  }
]

// Original task data before transformation
const originalMockTasks = [
  {
    id: "1",
    title: "Setup Authentication System",
    description: "Implement JWT-based authentication with login and registration",
    status: "done" as const,
    priority: "high" as const,
    labels: ["backend", "security"],
    projectId: "1",
    assigneeId: "2",
    assignee: mockUsers[1],
    project: { id: "1", name: "E-commerce Platform" },
    timelineStart: new Date("2024-01-15"),
    timelineEnd: new Date("2024-01-20"),
    estimatedHours: 16,
    loggedHours: 18,
    storyPoints: 8,
    issueType: "story" as const,
    sprintId: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    comments: [],
    logs: [],
  },
  {
    id: "2",
    title: "Design Product Catalog UI",
    description: "Create responsive product catalog with filtering and search",
    status: "in-progress" as const,
    priority: "medium" as const,
    labels: ["frontend", "ui"],
    projectId: "1",
    assigneeId: "3",
    assignee: mockUsers[2],
    project: { id: "1", name: "E-commerce Platform" },
    timelineStart: new Date("2024-01-18"),
    timelineEnd: new Date("2024-01-25"),
    estimatedHours: 24,
    loggedHours: 12,
    storyPoints: 13,
    issueType: "story" as const,
    sprintId: "1",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-22"),
    comments: [],
    logs: [],
  },
  {
    id: "3",
    title: "Implement Payment Gateway",
    description: "Integrate Stripe payment processing for checkout flow",
    status: "todo" as const,
    priority: "critical" as const,
    labels: ["backend", "payments"],
    projectId: "1",
    assigneeId: "2",
    assignee: mockUsers[1],
    project: { id: "1", name: "E-commerce Platform" },
    timelineStart: new Date("2024-01-25"),
    timelineEnd: new Date("2024-02-01"),
    estimatedHours: 20,
    loggedHours: 0,
    storyPoints: 13,
    issueType: "story" as const,
    sprintId: "2",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    comments: [],
    logs: [],
  },
  {
    id: "4",
    title: "User Profile Screen",
    description: "Design and implement user profile management screen",
    status: "in-progress" as const,
    priority: "medium" as const,
    labels: ["mobile", "ui"],
    projectId: "2",
    assigneeId: "4",
    assignee: mockUsers[3],
    project: { id: "2", name: "Mobile App Redesign" },
    timelineStart: new Date("2024-01-12"),
    timelineEnd: new Date("2024-01-19"),
    estimatedHours: 12,
    loggedHours: 8,
    storyPoints: 8,
    issueType: "story" as const,
    sprintId: "2",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
    comments: [],
    logs: [],
  },
  {
    id: "5",
    title: "API Endpoint Documentation",
    description: "Document all REST API endpoints with examples",
    status: "done" as const,
    priority: "low" as const,
    labels: ["documentation"],
    projectId: "3",
    assigneeId: "3",
    assignee: mockUsers[2],
    project: { id: "3", name: "API Documentation" },
    timelineStart: new Date("2024-01-05"),
    timelineEnd: new Date("2024-01-12"),
    estimatedHours: 8,
    loggedHours: 10,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-12"),
    comments: [],
    logs: [],
  },
  {
    id: "6",
    title: "Fix Login Button Not Working on Mobile",
    description: "Login button is not responding to touch events on mobile devices",
    status: "in-progress" as const,
    priority: "high" as const,
    labels: ["bug", "mobile", "frontend"],
    projectId: "1",
    assigneeId: "3",
    assignee: mockUsers[2],
    project: { id: "1", name: "E-commerce Platform" },
    timelineStart: new Date("2024-01-22"),
    timelineEnd: new Date("2024-01-24"),
    estimatedHours: 4,
    loggedHours: 2,
    storyPoints: 3,
    issueType: "bug" as const,
    sprintId: "1",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
    comments: [],
    logs: [],
  },
]

// Transform tasks to include subtasks and new status
export const mockTasks: TaskWithSubtasks[] = originalMockTasks.map(task => ({
  ...task,
  status: mockStatuses.find(s => 
    s.name.toLowerCase() === task.status || 
    s.category === (task.status === 'done' ? 'completed' : 
                    task.status === 'in-progress' ? 'in-progress' : 'not-started')
  ) || mockStatuses[0],
  subtasks: [
    {
      id: `subtask-${task.id}-1`,
      title: `Subtask 1 for ${task.title}`,
      description: "Initial subtask breakdown",
      status: mockStatuses[0],
      parentTaskId: task.id
    },
    {
      id: `subtask-${task.id}-2`,
      title: `Subtask 2 for ${task.title}`,
      description: "Secondary subtask breakdown",
      status: mockStatuses[1],
      parentTaskId: task.id
    }
  ]
}))

export const mockComments = [
  {
    id: "1",
    content: "Great progress on the authentication! The JWT implementation looks solid.",
    taskId: "1",
    userId: "1",
    user: mockUsers[0],
    parentId: null,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    replies: [],
  },
  {
    id: "2",
    content: "Thanks! I added some additional security measures as well.",
    taskId: "1",
    userId: "2",
    user: mockUsers[1],
    parentId: "1",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    replies: [],
  },
  {
    id: "3",
    content: "The UI mockups look great! Should we add a dark mode toggle?",
    taskId: "2",
    userId: "1",
    user: mockUsers[0],
    parentId: null,
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
    replies: [],
  },
]

export const mockTimeLogs = [
  {
    id: "1",
    taskId: "1",
    userId: "2",
    user: mockUsers[1],
    task: {
      id: "1",
      title: "Setup Authentication System",
      project: { id: "1", name: "E-commerce Platform" },
    },
    hoursSpent: 4,
    description: "Implemented JWT token generation and validation",
    logDate: new Date("2024-01-18"),
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "2",
    taskId: "2",
    userId: "3",
    user: mockUsers[2],
    task: {
      id: "2",
      title: "Design Product Catalog UI",
      project: { id: "1", name: "E-commerce Platform" },
    },
    hoursSpent: 6,
    description: "Created responsive grid layout and filter components",
    logDate: new Date("2024-01-20"),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    taskId: "4",
    userId: "4",
    user: mockUsers[3],
    task: {
      id: "4",
      title: "User Profile Screen",
      project: { id: "2", name: "Mobile App Redesign" },
    },
    hoursSpent: 3,
    description: "Designed profile layout and form validation",
    logDate: new Date("2024-01-17"),
    createdAt: new Date("2024-01-17"),
  },
]

export const mockActivity = [
  {
    id: "comment-1",
    type: "comment" as const,
    action: "commented on",
    user: mockUsers[0],
    task: {
      id: "1",
      title: "Setup Authentication System",
      project: { id: "1", name: "E-commerce Platform" },
    },
    content: "Great progress on the authentication! The JWT implementation looks solid.",
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "timelog-1",
    type: "timelog" as const,
    action: "logged time on",
    user: mockUsers[2],
    task: {
      id: "2",
      title: "Design Product Catalog UI",
      project: { id: "1", name: "E-commerce Platform" },
    },
    content: "6 hour(s): Created responsive grid layout and filter components",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "task-3",
    type: "task" as const,
    action: "created task",
    user: mockUsers[1],
    task: {
      id: "3",
      title: "Implement Payment Gateway",
      project: { id: "1", name: "E-commerce Platform" },
    },
    content: "Implement Payment Gateway",
    createdAt: new Date("2024-01-20"),
  },
]

// Mock notifications
export const mockNotifications = [
  {
    id: "1",
    type: "task_assigned" as const,
    title: "New Task Assigned",
    message: "You have been assigned to 'Implement Payment Gateway'",
    userId: "2",
    taskId: "3",
    projectId: "1",
    read: false,
    createdAt: new Date("2024-01-20T10:30:00"),
  },
  {
    id: "2",
    type: "task_completed" as const,
    title: "Task Completed",
    message: "Jane Smith completed 'Setup Authentication System'",
    userId: "1",
    taskId: "1",
    projectId: "1",
    read: false,
    createdAt: new Date("2024-01-20T14:15:00"),
  },
  {
    id: "3",
    type: "comment_added" as const,
    title: "New Comment",
    message: "John Doe commented on 'Design Product Catalog UI'",
    userId: "3",
    taskId: "2",
    projectId: "1",
    read: true,
    createdAt: new Date("2024-01-21T09:45:00"),
  },
  {
    id: "4",
    type: "deadline_approaching" as const,
    title: "Deadline Approaching",
    message: "'User Profile Screen' is due in 2 days",
    userId: "4",
    taskId: "4",
    projectId: "2",
    read: false,
    createdAt: new Date("2024-01-22T08:00:00"),
  },
  {
    id: "5",
    type: "task_created" as const,
    title: "Task Created",
    message: "John Doe created 'User Profile Screen'",
    userId: "1",
  },
  {
    id: "6",
    type: "task_updated" as const,
    title: "Task Updated",
    message: "Jane Smith updated 'Design Product Catalog UI'",
    userId: "2",
  },
  {
    id: "7",
    type: "task_deleted" as const,
    title: "Task Deleted",
    message: "John Doe deleted 'Implement Payment Gateway'",
    userId: "1",
  },
  {
    id: "8",
    type: "task_completed" as const,
    title: "Task Completed",
    message: "Jane Smith completed 'Design Product Catalog UI'",
    userId: "2",
  },
]

export const mockSprints =[
  {
    id: "1",
    name: "Sprint 1",
    goal: "Implement complete user authentication system with OAuth and email verification",
    status: "active",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-01-29"),
    totalStoryPoints: 34,
    completedStoryPoints: 18,
    totalTasks: 12,
    completedTasks: 6,
    teamMembers: [
      { id: "1", name: "John Doe", image: "" },
      { id: "2", name: "Jane Smith", image: "" },
      { id: "3", name: "Mike Johnson", image: "" },
    ],
  },
  {
    id: "2",
    name: "Sprint 2",
    goal: "Build comprehensive dashboard with real-time analytics and reporting",
    status: "planning",
    startDate: new Date("2024-01-30"),
    endDate: new Date("2024-02-13"),
    totalStoryPoints: 28,
    completedStoryPoints: 0,
    totalTasks: 8,
    completedTasks: 0,
    teamMembers: [
      { id: "1", name: "John Doe", image: "" },
      { id: "2", name: "Jane Smith", image: "" },
    ],
  },
  {
    id: "3",
    name: "Sprint 3",
    goal: "Initial project setup, CI/CD pipeline, and basic infrastructure",
    status: "completed",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-14"),
    totalStoryPoints: 16,
    completedStoryPoints: 16,
    totalTasks: 6,
    completedTasks: 6,
  },
  {
    id: "4",
    name: "Sprint 4",
    goal: "Initial project setup, CI/CD pipeline, and basic infrastructure",
    status: "completed",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-14"),
    totalStoryPoints: 16,
    completedStoryPoints: 16,
    totalTasks: 6,
    completedTasks: 6,
  },
]

// Mock project statistics
export const mockProjectStats = {
  totalProjects: 3,
  activeProjects: 2,
  completedProjects: 1,
  totalTasks: 5,
  completedTasks: 2,
  inProgressTasks: 2,
  todoTasks: 1,
  totalHoursLogged: 36,
  totalEstimatedHours: 80,
  overdueTasks: 0,
}

// Mock user statistics
export const mockUserStats = {
  totalTasksAssigned: 3,
  completedTasks: 1,
  inProgressTasks: 1,
  todoTasks: 1,
  totalHoursLogged: 18,
  averageTaskCompletion: 33.3,
  productivityScore: 85,
}

// Helper function to get current user (mock session)
// Note: getCurrentUser has been moved to hardcoded-auth.ts
// This function is kept for backward compatibility but should be replaced
export const getCurrentUser = () => mockUsers[0] // Always return first user as logged in user

// Helper function to get user notifications
export const getUserNotifications = (userId: string) => {
  return mockNotifications.filter(notification => notification.userId === userId)
}

// Helper function to get unread notification count
export const getUnreadNotificationCount = (userId: string) => {
  return mockNotifications.filter(notification => 
    notification.userId === userId && !notification.read
  ).length
}
